# Generated by Django 5.2.7 on 2025-10-14 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfalls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='yields_images/default.svg', null=True, upload_to='yields_images/')),
                ('crop_name', models.CharField(max_length=100)),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yield_tons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sowing_method', models.CharField(choices=[('ręczna', 'Ręczna'), ('maszynowa', 'Maszynowa')], max_length=20)),
                ('sowing_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('previous_crop', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('nawóz', 'Nawóz'), ('oprysk', 'Oprysk'), ('inne', 'Inne')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('yield_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='accounts.yield')),
            ],
        ),
        migrations.CreateModel(
            name='SoilPh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('soil_ph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_phs', to='accounts.yield')),
            ],
        ),
        migrations.CreateModel(
            name='MoistureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moisture_measurements', to='accounts.yield')),
            ],
        ),
    ]
